// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIaTQITWoSzuQRIZOL4ZhAVbleGP4sS18',
    appId: '1:626088962931:web:b6f45f63315ced876fb306',
    messagingSenderId: '626088962931',
    projectId: 'availalert-22e83',
    authDomain: 'availalert-22e83.firebaseapp.com',
    storageBucket: 'availalert-22e83.appspot.com',
    measurementId: 'G-NHK825KD5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRsWjWFqZ4W_9ay8S1auhvUkdtp6wahDs',
    appId: '1:626088962931:android:4fb345580d573f676fb306',
    messagingSenderId: '626088962931',
    projectId: 'availalert-22e83',
    storageBucket: 'availalert-22e83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB26TS8eUchnWBO8GLWiVxbVRV0Ee7oQeQ',
    appId: '1:626088962931:ios:9c2247228ad7361c6fb306',
    messagingSenderId: '626088962931',
    projectId: 'availalert-22e83',
    storageBucket: 'availalert-22e83.appspot.com',
    iosBundleId: 'com.example.availalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB26TS8eUchnWBO8GLWiVxbVRV0Ee7oQeQ',
    appId: '1:626088962931:ios:f22a29f0ba64fe0e6fb306',
    messagingSenderId: '626088962931',
    projectId: 'availalert-22e83',
    storageBucket: 'availalert-22e83.appspot.com',
    iosBundleId: 'com.example.availalert.RunnerTests',
  );
}
